name: Release Drafter

on:
  push:
    branches: [main]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update:
    uses: Camier/LAB/.github/workflows/release-drafter.yml@main
    secrets: inherit
